### ISSUE TITLE
Error on fast refresh

### ISSUE THREAD

**Issue by kesha-antonov** [CharlesStover/use-dimensions#5]
<img width="409" alt="Screenshot 2022-11-04 at 14 18 09" src="https://user-images.githubusercontent.com/11584712/199960489-061bf830-553f-4840-b0c1-ac23edb5b9b7.png">

**Comment by quisido** [comment]
Sorry for the late reply to this. This is an old repository that no longer has CI/CD support for updates. It's not impossible to resolve this, but it's just been lower priority, as I am not a React Native developer to be able to test this on newer versions of `react-native`.

This error appears as though `require('react-native').Dimensions.get()` returns `Dimensions | undefined`, but is currently typed as `Dimensions`.

**Comment by quisido** [comment]
I'll try to have a revision under `2.0` this week since it looks like newer versions of React Native use `EmitterSubscription` instead of `removeEventHandler`. I'll close this issue when that revision gets posted.

If you are using `useWindowDimensions`, you should still be able to access it by importing directly from `react-native`.

If you are wanting `useScreenDimensions`, that will be included in the 2.0 release (alongside the `useWindowDimensions` hook).
